---
title: "City Permits"
author: "Alan Jackson"
date: "June 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")
library("stringr") # string tools
library("lettercase") # fiddle with letter case
library("lubridate")

options(stringsAsFactors = FALSE)

knitr::opts_chunk$set(echo = TRUE)
```

## Read in the downloaded file

A file may be downloaded from https://cohgis-mycity.opendata.arcgis.com/datasets/permits-wm-structural?geometry=-97.509%2C29.379%2C-93.263%2C30.213

We'll read it in. It is already (mostly) geocoded, so we'll skip that step.


```{r read report}

infile <- "/home/ajackson/Dropbox/Rprojects/CityPermits/Permits_wm_Structural.csv"

Permits <- read_csv(infile) %>% 
  select(X, Y, OBJECTID, Match_addr, PROJ_DESC, RECORDED_DATE) %>%
  drop_na(X)
  
#   rename columns

names(Permits) <- c("Lon", "Lat", "ID", "Address", "Description", "Date")


```

## Save output


```{r Save output, echo=FALSE}

saveRDS(Permits, paste("~/Dropbox/Rprojects/CityPermits/StructuralPermits.rds", sep=""))

```

##  geocoder from permit database

```{r geocoding file}

library(postmastr)

geo1 <- pm_identify(Permits, var="Address")
geo2 <- pm_prep(geo1, var="Address")

#   zip

pm_postal_none(geo2)
geo2 <- pm_postal_detect(geo2) %>% 
  filter(pm.hasZip==TRUE) %>% 
  select(-pm.hasZip)
geo2 <- pm_postal_parse(geo2)

#   No city or state

#   house numbers

geo2 <- pm_house_parse(geo2)

#   Street names have odd letters in front of them sometimes

geo2$pm.address <- str_remove(geo2$pm.address, "^[A-D,F-H,M,R] ")

#   House numbers may have attached unit numbers

geo2$pm.house <- str_remove(geo2$pm.house, "[A-Z#][0-9]*")

#   parse directionals and suffixes

geo2 <- pm_streetDir_parse(geo2)
geo2 <- pm_streetSuf_parse(geo2)

#   Street names

geo2 <- pm_street_parse(geo2)

#   Add parsed bits back into original

geo3 <- pm_replace(geo2, source=geo1)

#   Rebuild addresses

geo3 <- pm_rebuild(geo3, start=pm.preDir, end=pm.sufDir, keep_parsed="yes")

#   Create block range

geo3 <- geo3 %>% 
  mutate(block_range=paste0(
                 as.character(round(as.numeric(pm.house)/100)),
                 "00-",
                 as.character(round(as.numeric(pm.house)/100)),
                 "99"
                 )) 

#   remove duplicates

geo3 <- geo3 %>% 
  select(Lon, Lat, Address, block_range, pm.house, pm.address, pm.zip) 

geo3 <- geo3 %>% 
  na.omit() %>% 
  unique()

geo3 <- geo3 %>% 
  mutate(Address=paste0(block_range, " ", 
                       pm.address, " , ", 
                       "Houston, TX", " ",
                       pm.zip))

saveRDS(geo3, "~/Dropbox/CrimeStats/PermitDB_Geocode.rds")

```








